### ISSUE TITLE
Configurable export frontend

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/server#917]

**Comment by ZuzanaOdstrcilova** [comment]
Here is export in figma
https://www.figma.com/file/UCvcqHZe6owmJV5QolBMoj/tolgee-tasks?node-id=38%3A714

and more ideas
https://www.figma.com/file/YZOdC2Tgt34q1dzqvYNjG5/Tolgee-drafts?node-id=13%3A608

**Comment by ZuzanaOdstrcilova** [comment]
we will export:
- zip file for more languages
- one file (.json etc.) for one language (+from the dashboard by choosing export in menu belonging to concrete language)
- we could change a name on the export button ("export as zip", ...), or have the same "export" - I prefer the same name

scope:
- for now we could hide it or add tooltip, info button
